### ISSUE TITLE
API Improvements

### ISSUE THREAD

**Issue by conlan** [NoahZinsmeister/uniswap-api#12]
- [x] Issue #10 - Include Transaction Index
- [ ] Issue #4 - Implement Fee Calculation
- [ ] Issue #11 - Fill out remainder of documentation for all endpoints
